### PR TITLE
Remove channel picker

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR removes the channel picker from the subscriptions modal. There is some flakiness and the complexity will be removed for v1 of the zendesk app.

* remove channel picker select field
* when client searches for triggers, include the channelID so that the client results are scoped only to the current channel
* when a new sub is selected:
  * show hint `Name of your subscription` instead of actual text 

#### Ticket Link
- [x] https://mattermost.atlassian.net/browse/MM-35378 - MM Apps - Znedesk remove channel picker in subscriptions modal
- [x] https://mattermost.atlassian.net/browse/MM-35379 - MM Apps - Remove default text from the subscription name field for new subscriptions form

### CODE REVIEW

**Comment by mickmister** [comment]
> There is some flakiness and the complexity will be removed for v1 of the zendesk app

@jfrerich Can you go in detail with these two points?

**Comment by jfrerich** [comment]
> > There is some flakiness and the complexity will be removed for v1 of the zendesk app
> 
> @jfrerich Can you go in detail with these two points?

There is an issue where a sub was getting created, but stored in the wrong channel. This is likely more of a bug than actual flakiness in the framework.  However, the decision was to just remove the channel picker for now. I might add it back later

**Comment by jfrerich** [comment]
@DHaussermann, if QA approves this one, I am going to merge so that we can get this into master.

**Review by catalintomai — APPROVED** [review]

**Comment by DHaussermann** [comment]
Both fixes were tested. 
LGTM!

Thanks @jfrerich please merge.

**Review by DHaussermann — APPROVED** [review]

**Pull request merged**
