### PR TITLE
Make Zendesk App runnable in AWS lambda

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR makes the Zendesk runnable as an AWS lambda function. `npm run package` builds `dist/bundle.zip`, which the deploy script in the Apps plugin can then provision.

The Apps is still runnable as an HTTP app.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32724

### CODE REVIEW

**Review by iomodo — APPROVED** [review]
Looks good. Can you just add in doc how to build/run local and non-local app?

**Comment by hanzei** [comment]
> Can you just add in doc how to build/run local and non-local app

There is already docs on how to run the local app. Would you be fine if we link to https://github.com/mattermost/mattermost-plugin-apps/blob/MM-32702_appsctl/README.md#provisioning for the AWS app?

**Review by jfrerich — APPROVED** [review]
Thanks, @hanzei!  I think I comprehend what is going on here, but will have to trust your judgment.

**Comment by hanzei** [comment]
Messed up the merge :confused: No squashed commits

**Pull request merged**
