### PR TITLE
[MM-36410] update png icon

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR updates the .png image so the bot profile pic is not cropped. Thanks, @Rina-dsg for the image!

before: 
image

after:
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36410

### CODE REVIEW

**Review by Rina-dsg — APPROVED** [review]

**Comment by DHaussermann** [comment]
@jfrerich the switch for the LHS and profile image are working. But, there is one change that I did not expect. I seems replacing the at asset also change the autocomplete icon.
image

Is it possible to have both assets and have just the autocomplete use the old one to leave the auto-complete unchanged? The issue for the related Jira ticket was to change the profile image where cropping is an issue.

**Comment by jfrerich** [comment]
@DHaussermann and @Rina-dsg, the latest commit keeps the larger Zendesk Icon for every command that is not the profile image. This includes slash commands and form icons. 

There is one improvement that I'd like, but it would require changes to the app framework.  The same icon that is used for the profile image is used for the Install Form Icon.

image

**Comment by jfrerich** [comment]
I'd prefer to use the larger image in this form, but it is not a deal breaker.

**Comment by jfrerich** [comment]
What do y'all think of increasing the size of the icon for the profile image so that it fills more of the profile image area?  I feel like it is a bit small

image

**Comment by DHaussermann** [comment]
@jfrerich and @Rina-dsg  I'm okay with increasing it as long as the edges of the Zendesk logo remain visible. I was unsure by how much the webapp crps profile images so it may be that a slightly larger icon will still work.

**Review by catalintomai — APPROVED** [review]

**Comment by jfrerich** [comment]
@Rina-dsg, can you provide a slightly larger avatar asset for the Zendesk bot?  I'd like it to fill the available space a bit more.  For reference, here is the Jira ticket where the images were attached. Thank you!

**Comment by Rina-dsg** [comment]
Sure! Will send you soon

**Comment by Rina-dsg** [comment]
@jfrerich Assets: [Zendesk - large logo.zip](https://github.com/mattermost/mattermost-app-zendesk/files/6844616/Zendesk.-.large.logo.zip)

**Comment by jfrerich** [comment]
Looks great! Thanks, @Rina-dsg 
image

**Comment by jfrerich** [comment]
Dylan will test at Release.

**Pull request merged**
