### PR TITLE
Update version to 0.3.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Ticket Link

https://github.com/mattermost/mattermost-app-zendesk/issues/102

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann I think the release is ready for your final approval, right @mickmister?

**Comment by mickmister** [comment]
@DHaussermann Here's the lambda function bundle for this PR

https://output.circle-artifacts.com/output/job/89695516-817f-4058-88eb-261451924fae/artifacts/0/dist/bundle.zip

**Comment by DHaussermann** [comment]
Thanks @mickmister I will look at this tomorrow.

**Review by DHaussermann — APPROVED** [review]
Smoke testing done. No new issues 
- Setup webhook
- Subscriptions can be created 
- Subscription can updated
- Spot checked subscription delivery for some fields
- Help does not show admin commands for all users
- Icon works on app bar (icon is cropped too much) 
- Explored bindings availability looks normal. Bindings removed from UI when app is disabled   
- Install process
- Uninstall and re-install process 

LGTM!
cc @mickmister

**Pull request merged**
