### PR TITLE
Improvement - Updated Comments to Sentence Case

### LINKED ISSUE #76: Start comments with Uppercase letter.
Also noticed a lot of sentences here are started with a lowercase letter. Probably not a big deal because they're comments, but I think we consistently start comments with a capital letter in our projects, especially if it's a sentence. This doesn't apply to sentences that start with a lowercase function name.

```suggestion
// Conditions are fetched only once when the modal opens and stores in state.
```

_Originally posted by @mickmister in https://github.com/mattermost/mattermost-app-zendesk/pull/74#discussion_r696179430_

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

#### Summary
This PR Updates the case of comments in the files of the repository to Sentence Case

#### Ticket Link
This PR Fixes #76 

**Note for Reviewers:**
I've not updated the case of some of the comments as they were function names. Please do lmk if I've to update the same and I'll gladly do it :)

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@jfrerich No probs, I'll take a look at the conflicts and fix them soon :)

**Comment by adithyaakrishna** [comment]
@jfrerich Is it fine if I can resolve them through GitHub itself?

**Comment by jfrerich** [comment]
Sure, that's fine if you want to resolve through GitHub :)

**Comment by adithyaakrishna** [comment]
Ack will fix it. 
Also my bad instead of editing the comment I deleted it, smh 🤦🏻

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @adithyaakrishna

**Pull request merged**
