### PR TITLE
Improvement - Updated to Mattermost Elint Rules

### LINKED ISSUE #77: Use Mattermost eslint rules.
I assume some of these are removed because they are not used. Is there a lint-like(or other tool) that we can use to detect unused vars?

_Originally posted by @catalintomai in https://github.com/mattermost/mattermost-app-zendesk/pull/74#discussion_r702463496_

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna aadithya794@gmail.com

#### Summary
This PR Updates the repo files to use Mattermost Eslint Rules and Added Import Sort to the Rules

I've also Addressed this specific comment in the issue in the PR as well, https://github.com/mattermost/mattermost-app-zendesk/issues/77#issuecomment-914335178

#### Ticket Link
This PR Fixes #77

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@jfrerich Updated this MR Just Now to Resolve Conflicts :)

**Comment by adithyaakrishna** [comment]
@mickmister I think it was due to @jfrerich 's PR being merged and Me updating the branch to put it in line with the changes in master. AFAIK I didn't change any logic in this PR. 

CC @jfrerich

**Comment by jfrerich** [comment]
@adithyaakrishna, I temporarily changed the base branch to `MM-33384-dynamic-subscriptions-before-squashing` (just a random branch) and then back to `master`.  Is the PR is the state you would expect now?

**Comment by adithyaakrishna** [comment]
Yayyy 🎉 
Thanks @mickmister

**Comment by mickmister** [comment]
Hi @adithyaakrishna, it looks like there are some merge conflicts with this PR. Do you mind resolving these so we can merge the PR? Thanks!

**Comment by adithyaakrishna** [comment]
@mickmister I used GitHub itself to resolve the conflicts, hope its okay :)

**Comment by mickmister** [comment]
Thanks for your contribution @adithyaakrishna :tada:

**Pull request merged**
