### PR TITLE
[MM-40475] Update to latest version of apps plugin

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Targets: https://github.com/mattermost/mattermost-plugin-apps/pull/298

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40475

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
Thanks @hanzei! I like bringing the root_url into the http object.

**Comment by DHaussermann** [comment]
@hanzei I tested this with theses 2 PRs to see if install and authentication was still functional
https://github.com/mattermost/mattermost-server/pull/19178
https://github.com/mattermost/mattermost-plugin-apps/pull/291 

Should this only be tested against the `master` branches of Apps and server?

I see the Zendesk app crash. 
The Zendesk console shows 
```
/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/utils/utils.js:162
    if (oauth2user && oauth2user.token.access_token && oauth2user.token.access_token !== '') {
                                       ^

TypeError: Cannot read properties of undefined (reading 'access_token')
    at Object.isConnected (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/utils/utils.js:162:40)
    at Object.getBindings (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/bindings/index.js:13:30)
    at /Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:46:31
    at step (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:33:23)
    at Object.next (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:14:53)
    at /Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:4:12)
    at exports.fBindings (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/dist/restapi/fBindings.js:42:50)
    at Layer.handle [as handle_request] (/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-app-zendesk/node_modules/express/lib/router/layer.js:95:5)
[nodemon] app crashed - waiting for file changes before starting...
```

Mattermost UI shows this error but it may only be occurring after the app has already crashed.
image

**Comment by hanzei** [comment]
@DHaussermann Zendesk is still broken and this PR doesn't completely fix this. See https://community-daily.mattermost.com/core/pl/r7ao6ykfqff3fk13kkrjeoch6r

**Comment by hanzei** [comment]
@levb Gentle reminder to review this PR

**Comment by hanzei** [comment]
@DHaussermann The error above will be fixed with https://github.com/mattermost/mattermost-app-zendesk/pull/91

**Comment by hanzei** [comment]
@DHaussermann  https://github.com/mattermost/mattermost-app-zendesk/pull/91  is merged. Please test again.

**Review by levb — APPROVED** [review]

**Pull request merged**
